### ISSUE TITLE
Ctrl+Enter to insert ; without new line

### ISSUE THREAD

**Issue by demisx** [nechor/brackets-semicenter#1]
Hi, 
Thank you for writing this extension. I find it very useful. Would it be possible to add a `Ctrl+Enter` key map that adds the semicolon to the end of the line, but without inserting a new line similar to how `Alt+Enter` does it now? Quite often, we need to add a semicolon to the current line, but still have the cursor where it is.

Thank you.

**Comment by nechor** [comment]
It's done. Shortcut ctrl+Enter is already taken (try it), but I did it under alt+semicolon.

**Comment by demisx** [comment]
Thank you. Hitting `Alt+;` also adds `...` after the semicolon, i.e.:

``` js
console.log(stdout)  Alt+; //=> console.log(stdout);… 
```

**Comment by nechor** [comment]
Hmm... Can't reproduce this... Can you tell mi which alt you use - left or right?

**Comment by nechor** [comment]
Maybe try to uninstall semicenter and press alt+;  It could be that some other extension works under this shortcut.

**Comment by demisx** [comment]
You are right. Some other extension adds this `...`. Is there any way to tell the semicenter to override this keybinding. I never use it to insert `...`

**Comment by nechor** [comment]
What if somebody else also write code to override my shortcuts? :-)

**Comment by demisx** [comment]
@nechor Well, I thought maybe there was a way to do this at the user level, not the extension level. I am new to Brackets. I see there will be more conflicts in the future when more extensions are written.
